/*
 * Decompiled with CFR 0.1.1 (FabricMC 57d88659).
 */
package net.minecraft.structure;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import net.minecraft.registry.Registerable;
import net.minecraft.registry.RegistryEntryLookup;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.entry.RegistryEntry;
import net.minecraft.structure.pool.StructurePool;
import net.minecraft.structure.pool.StructurePoolElement;
import net.minecraft.structure.pool.StructurePools;
import net.minecraft.structure.processor.StructureProcessorList;
import net.minecraft.structure.processor.StructureProcessorLists;
import net.minecraft.world.gen.feature.PlacedFeature;
import net.minecraft.world.gen.feature.UndergroundPlacedFeatures;

public class AncientCityOutskirtsGenerator {
    public static void bootstrap(Registerable<StructurePool> poolRegisterable) {
        RegistryEntryLookup<PlacedFeature> lv = poolRegisterable.getRegistryLookup(RegistryKeys.PLACED_FEATURE);
        RegistryEntry.Reference<PlacedFeature> lv2 = lv.getOrThrow(UndergroundPlacedFeatures.SCULK_PATCH_ANCIENT_CITY);
        RegistryEntryLookup<StructureProcessorList> lv3 = poolRegisterable.getRegistryLookup(RegistryKeys.PROCESSOR_LIST);
        RegistryEntry.Reference<StructureProcessorList> lv4 = lv3.getOrThrow(StructureProcessorLists.ANCIENT_CITY_GENERIC_DEGRADATION);
        RegistryEntry.Reference<StructureProcessorList> lv5 = lv3.getOrThrow(StructureProcessorLists.ANCIENT_CITY_WALLS_DEGRADATION);
        RegistryEntryLookup<StructurePool> lv6 = poolRegisterable.getRegistryLookup(RegistryKeys.TEMPLATE_POOL);
        RegistryEntry.Reference<StructurePool> lv7 = lv6.getOrThrow(StructurePools.EMPTY);
        StructurePools.register(poolRegisterable, "ancient_city/structures", new StructurePool(lv7, ImmutableList.of(Pair.of(StructurePoolElement.ofEmpty(), 7), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/barracks", lv4), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/chamber_1", lv4), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/chamber_2", lv4), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/chamber_3", lv4), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/sauna_1", lv4), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/small_statue", lv4), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/large_ruin_1", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/tall_ruin_1", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/tall_ruin_2", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/tall_ruin_3", lv4), 2), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/tall_ruin_4", lv4), 2), new Pair[]{Pair.of(StructurePoolElement.ofList(ImmutableList.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/camp_1", lv4), StructurePoolElement.ofProcessedSingle("ancient_city/structures/camp_2", lv4), StructurePoolElement.ofProcessedSingle("ancient_city/structures/camp_3", lv4))), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/medium_ruin_1", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/medium_ruin_2", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/small_ruin_1", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/small_ruin_2", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/large_pillar_1", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/structures/medium_pillar_1", lv4), 1), Pair.of(StructurePoolElement.ofList(ImmutableList.of(StructurePoolElement.ofSingle("ancient_city/structures/ice_box_1"))), 1)}), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "ancient_city/sculk", new StructurePool(lv7, ImmutableList.of(Pair.of(StructurePoolElement.ofFeature(lv2), 6), Pair.of(StructurePoolElement.ofEmpty(), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "ancient_city/walls", new StructurePool(lv7, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_corner_wall_1", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_intersection_wall_1", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_lshape_wall_1", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_1", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_2", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_1", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_2", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_3", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_4", lv5), 4), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_passage_1", lv5), 3), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/ruined_corner_wall_1", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/ruined_corner_wall_2", lv5), 1), new Pair[]{Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/ruined_horizontal_wall_stairs_1", lv5), 2), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/ruined_horizontal_wall_stairs_2", lv5), 2), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/ruined_horizontal_wall_stairs_3", lv5), 3), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/ruined_horizontal_wall_stairs_4", lv5), 3)}), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "ancient_city/walls/no_corners", new StructurePool(lv7, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_1", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_2", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_1", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_2", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_3", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_4", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_stairs_5", lv5), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/walls/intact_horizontal_wall_bridge", lv5), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "ancient_city/city_center/walls", new StructurePool(lv7, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/bottom_1", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/bottom_2", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/bottom_left_corner", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/bottom_right_corner_1", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/bottom_right_corner_2", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/left", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/right", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/top", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/top_right_corner", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city_center/walls/top_left_corner", lv4), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "ancient_city/city/entrance", new StructurePool(lv7, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city/entrance/entrance_connector", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city/entrance/entrance_path_1", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city/entrance/entrance_path_2", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city/entrance/entrance_path_3", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city/entrance/entrance_path_4", lv4), 1), Pair.of(StructurePoolElement.ofProcessedSingle("ancient_city/city/entrance/entrance_path_5", lv4), 1)), StructurePool.Projection.RIGID));
    }
}

