/*
 * Decompiled with CFR 0.1.1 (FabricMC 57d88659).
 */
package net.minecraft.structure;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import net.minecraft.registry.Registerable;
import net.minecraft.registry.RegistryEntryLookup;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.entry.RegistryEntry;
import net.minecraft.structure.pool.StructurePool;
import net.minecraft.structure.pool.StructurePoolElement;
import net.minecraft.structure.pool.StructurePools;
import net.minecraft.structure.processor.StructureProcessorList;
import net.minecraft.structure.processor.StructureProcessorLists;

public class BastionHoglinStableData {
    public static void bootstrap(Registerable<StructurePool> poolRegisterable) {
        RegistryEntryLookup<StructureProcessorList> lv = poolRegisterable.getRegistryLookup(RegistryKeys.PROCESSOR_LIST);
        RegistryEntry.Reference<StructureProcessorList> lv2 = lv.getOrThrow(StructureProcessorLists.STABLE_DEGRADATION);
        RegistryEntry.Reference<StructureProcessorList> lv3 = lv.getOrThrow(StructureProcessorLists.SIDE_WALL_DEGRADATION);
        RegistryEntryLookup<StructurePool> lv4 = poolRegisterable.getRegistryLookup(RegistryKeys.TEMPLATE_POOL);
        RegistryEntry.Reference<StructurePool> lv5 = lv4.getOrThrow(StructurePools.EMPTY);
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/starting_pieces", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/starting_stairs_0", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/starting_stairs_1", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/starting_stairs_2", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/starting_stairs_3", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/starting_stairs_4", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/mirrored_starting_pieces", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/stairs_0_mirrored", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/stairs_1_mirrored", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/stairs_2_mirrored", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/stairs_3_mirrored", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/starting_pieces/stairs_4_mirrored", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/wall_bases", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/walls/wall_base", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/walls", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/walls/side_wall_0", lv3), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/walls/side_wall_1", lv3), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/stairs", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_1_0", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_1_1", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_1_2", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_1_3", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_1_4", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_2_0", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_2_1", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_2_2", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_2_3", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_2_4", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_3_0", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_3_1", lv2), 1), new Pair[]{Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_3_2", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_3_3", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/stairs/stairs_3_4", lv2), 1)}), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/small_stables/inner", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/small_stables/inner_0", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/small_stables/inner_1", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/small_stables/inner_2", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/small_stables/inner_3", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/small_stables/outer", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/small_stables/outer_0", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/small_stables/outer_1", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/small_stables/outer_2", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/small_stables/outer_3", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/large_stables/inner", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/inner_0", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/inner_1", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/inner_2", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/inner_3", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/inner_4", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/large_stables/outer", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/outer_0", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/outer_1", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/outer_2", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/outer_3", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/large_stables/outer_4", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/posts", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/posts/stair_post", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/posts/end_post", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/ramparts", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/ramparts/ramparts_1", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/ramparts/ramparts_2", lv2), 1), Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/ramparts/ramparts_3", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/rampart_plates", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/rampart_plates/rampart_plate_1", lv2), 1)), StructurePool.Projection.RIGID));
        StructurePools.register(poolRegisterable, "bastion/hoglin_stable/connectors", new StructurePool(lv5, ImmutableList.of(Pair.of(StructurePoolElement.ofProcessedSingle("bastion/hoglin_stable/connectors/end_post_connector", lv2), 1)), StructurePool.Projection.RIGID));
    }
}

